name: application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management (équivalent Pinia)
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API (équivalent Axios)
  dio: ^5.3.4
  json_annotation: ^4.8.1
  
  # JWT & Auth
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  
  # Navigation (équivalent Vue Router)
  go_router: ^12.1.3
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Calendar (équivalent FullCalendar)
  table_calendar: ^3.0.9
  
  # Forms & Validation (équivalent Zod)
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Utils
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true