name: assbt
description: Association Sportive de Subaquatique du Bassin Toulonnais
publish_to: 'none'

version: 0.1.0-beta+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management (équivalent Pinia)
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API (équivalent Axios)
  dio: ^5.3.4
  json_annotation: ^4.8.1
  
  # JWT & Auth
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  
  # Navigation (équivalent Vue Router)
  go_router: ^16.2.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Calendar (équivalent FullCalendar)
  table_calendar: ^3.0.9
  
  # Forms & Validation (équivalent Zod)
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Utils
  equatable: ^2.0.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/

# Configuration pour les icônes de lancement
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#134074"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"